vich_uploader:
    db_driver: orm
    mappings:
        film_images:
            uri_prefix:         '%app.path.film_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.film_images%'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
